Aggressive Instruction Finder=false
Aggressive Instruction Finder.Create Analysis Bookmarks=false
Decompiler Switch Analysis=true
Non-Returning Functions - Discovered=true
Function Start Search=true
Decompiler Parameter ID=true
